
/** USER REDUCER TYPES */
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';

/** UI REDUCER TYPES */
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';


/** DATA REDUCER TYPES */
export const SET_SPORE = 'SET_SPORE'
export const SET_SPORES = 'SET_SPORES'
export const LOADING_DATA = 'LOADING_DATA'
export const LIKE_SPORE = 'LIKE_SPORE'
export const UNLIKE_SPORE = 'UNLIKE_SPORE'
export const DELETE_SPORE = 'DELETE_SPORE'
export const POST_SPORE = 'POST_SPORE';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';